### ISSUE TITLE
Open source license of this library?

### ISSUE THREAD

**Issue by francais-harry** [championswimmer/Lifelog-Android-Library#2]
I wonder if you could specify license of this project by LICENSE file for example, so that I can feel free to import to my app. I hope I can use this with non strict license such as Apache 2.0 or BSD.

**Comment by championswimmer** [comment]
Added an APache 2.0 license. Go forward and use it :+1:

**Comment by francais-harry** [comment]
Thanks a lot for your action. No pressure, but could you look into #3 too when you have time?
